default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: jhoynerk
  password: test

development:
  <<: *default
  database: sistemaIJO_dev

test:
  <<: *default
  database: sistemaIJO_test

production:
  <<: *default
  database: sistemaIJO_test
